AWSTemplateFormatVersion: '2010-09-09'

Description: Create database infrastructure for aws-iac-study

Parameters:
  DBMasterPassword:
    Type: String
    NoEcho: true
    Description: Master password for RDS

Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      VpcId: !ImportValue aws-iac-study-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue aws-iac-study-ec2-sg-id
      Tags:
        - Key: Name
          Value: aws-iac-study-rds-sg

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !ImportValue aws-iac-study-private-subnet-a-id
        - !ImportValue aws-iac-study-private-subnet-c-id
      Tags:
        - Key: Name
          Value: aws-iac-study-db-subnet-group

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: aws-iac-study-db
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp3

      MasterUsername: admin
      MasterUserPassword: !Ref DBMasterPassword

      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup

      MultiAZ: true
      PubliclyAccessible: false